In [1]:
import pandas as pd

In [2]:
data_2015 = pd.read_csv('2015.csv')
data_2016 = pd.read_csv('2016.csv')
data_2017 = pd.read_csv('2017.csv')
data_2018 = pd.read_csv('2018.csv')
data_2019 = pd.read_csv('2019.csv')

In [3]:
data_2015.columns.tolist()

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Standard Error',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual']

In [4]:
data_2015.rename(columns={'Happiness Rank':'2015 Happiness Rank',
                         'Happiness Score':'2015 Happiness Score',
                         'Standard Error':'2015 Standard Error',
                         'Economy (GDP per Capita)':'2015 Economy (GDP per Capita)',
                         'Family':'2015 Family',
                         'Health (Life Expectancy)':'2015 Health (Life Expectancy)',
                         'Freedom':'2015 Freedom',
                         'Trust (Government Corruption)':'2015 Trust (Government Corruption)',
                         'Generosity':'2015 Generosity',
                         'Dystopia Residual':'2015 Dystopia Residual'}, inplace=True)

In [5]:
data_2016.columns.tolist()

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Lower Confidence Interval',
 'Upper Confidence Interval',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual']

In [6]:
data_2016.rename(columns={'Happiness Rank':'2016 Happiness Rank',
                         'Happiness Score':'2016 Happiness Score',
                         'Economy (GDP per Capita)':'2016 Economy (GDP per Capita)',
                         'Family':'2016 Family',
                         'Health (Life Expectancy)':'2016 Health (Life Expectancy)',
                         'Freedom':'2016 Freedom',
                         'Trust (Government Corruption)':'2016 Trust (Government Corruption)',
                         'Generosity':'2016 Generosity',
                         'Dystopia Residual':'2016 Dystopia Residual'}, inplace=True)

In [7]:
data_2017.columns.tolist()

['Country',
 'Happiness.Rank',
 'Happiness.Score',
 'Whisker.high',
 'Whisker.low',
 'Economy..GDP.per.Capita.',
 'Family',
 'Health..Life.Expectancy.',
 'Freedom',
 'Generosity',
 'Trust..Government.Corruption.',
 'Dystopia.Residual']

In [8]:
data_2017.rename(columns={'Happiness.Rank':'2017 Happiness Rank',
                         'Happiness.Score':'2017 Happiness Score',
                         'Economy..GDP.per.Capita.':'2017 Economy (GDP per Capita)',
                         'Family':'2017 Family',
                         'Health..Life.Expectancy.':'2017 Health (Life Expectancy)',
                         'Freedom':'2017 Freedom',
                         'Trust..Government.Corruption.':'2017 Trust (Government Corruption)',
                         'Generosity':'2017 Generosity',
                         'Dystopia.Residual':'2017 Dystopia Residual'}, inplace=True)

In [9]:
data_2018.columns.tolist()

['Overall rank',
 'Country or region',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [10]:
data_2018.rename(columns={'Overall rank':'2018 Happiness Rank',
                         'Score':'2018 Happiness Score',
                         'GDP per capita':'2018 Economy (GDP per Capita)',
                         'Social support':'2018 Family',
                         'Healthy life expectancy':'2018 Health (Life Expectancy)',
                         'Freedom to make life choices':'2018 Freedom',
                         'Perceptions of corruption':'2018 Trust (Government Corruption)',
                         'Generosity':'2018 Generosity',
                         'Country or region':'Country'
                         }, inplace=True)

In [12]:
data_2018.groupby("Country").count()

,2018 Happiness Rank,2018 Happiness Score,2018 Economy (GDP per Capita),2018 Family,2018 Health (Life Expectancy),2018 Freedom,2018 Generosity,2018 Trust (Government Corruption)
Country,,,,,,,,
Afghanistan,1,1,1,1,1,1,1,1
Albania,1,1,1,1,1,1,1,1
Algeria,1,1,1,1,1,1,1,1
Angola,1,1,1,1,1,1,1,1
Argentina,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...
Venezuela,1,1,1,1,1,1,1,1
Vietnam,1,1,1,1,1,1,1,1
Yemen,1,1,1,1,1,1,1,1
Zambia,1,1,1,1,1,1,1,1
Zimbabwe,1,1,1,1,1,1,1,1

In [13]:
data_2019.columns.tolist()

['Overall rank',
 'Country or region',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [14]:
data_2019.rename(columns={'Overall rank':'2019 Happiness Rank',
                         'Score':'2019 Happiness Score',
                         'GDP per capita':'2019 Economy (GDP per Capita)',
                         'Social support':'2019 Family',
                         'Healthy life expectancy':'2019 Health (Life Expectancy)',
                         'Freedom to make life choices':'2019 Freedom',
                         'Perceptions of corruption':'2019 Trust (Government Corruption)',
                         'Generosity':'2019 Generosity',
                         'Country or region':'Country'}, inplace=True)

In [15]:
merge=pd.merge(data_2015,data_2016,on="Country",how="outer")

In [16]:
merge=pd.merge(merge,data_2017,on="Country",how="outer")

In [17]:
merge=pd.merge(merge,data_2018,on="Country",how="outer")

In [18]:
merge=pd.merge(merge,data_2019,on="Country",how="outer")

In [19]:
merge

,Country,Region_x,2015 Happiness Rank,2015 Happiness Score,2015 Standard Error,2015 Economy (GDP per Capita),2015 Family,2015 Health (Life Expectancy),2015 Freedom,2015 Trust (Government Corruption),...,2018 Generosity,2018 Trust (Government Corruption),2019 Happiness Rank,2019 Happiness Score,2019 Economy (GDP per Capita),2019 Family,2019 Health (Life Expectancy),2019 Freedom,2019 Generosity,2019 Trust (Government Corruption)
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,"Hong Kong S.A.R., China",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,Trinidad & Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.171,0.019,39.0,6.192,1.231,1.477,0.713,0.489,0.185,0.016
167,Northern Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.179,0.154,64.0,5.718,1.263,1.252,1.042,0.417,0.191,0.162
168,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,84.0,5.274,0.983,1.294,0.838,0.345,0.185,0.034
169,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,120.0,4.516,0.308,0.939,0.428,0.382,0.269,0.167

In [20]:
merge.to_csv('2015-2019 Happiness Score.csv')